export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Prose Protocol Design System
        background: '#faf8ff',
        surface: '#faf8ff',
        'surface-dim': '#dad9e1',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3fa',
        'surface-container': '#eeedf4',
        'surface-container-high': '#e9e7ef',
        'surface-container-highest': '#e3e1e9',
        'on-surface': '#1a1b21',
        'on-surface-variant': '#444651',
        'inverse-surface': '#2f3036',
        'inverse-on-surface': '#f1f0f7',
        outline: '#757682',
        'outline-variant': '#c5c5d3',
        'surface-tint': '#4059aa',
        primary: '#1e3a8a',
        'on-primary': '#ffffff',
        'primary-container': '#1e3a8a',
        'on-primary-container': '#90a8ff',
        'inverse-primary': '#b6c4ff',
        'primary-fixed': '#4059aa',
        'primary-fixed-dim': '#6b7adb',
        'on-primary-fixed': '#ffffff',
        'on-primary-fixed-variant': '#1e3a8a',
        secondary: '#505f76',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0e1fb',
        'on-secondary-container': '#54647a',
        'secondary-fixed': '#6a7fb0',
        'secondary-fixed-dim': '#8b9ac9',
        'on-secondary-fixed': '#ffffff',
        'on-secondary-fixed-variant': '#505f76',
        tertiary: '#4b1c00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6e2c00',
        'on-tertiary-container': '#f39461',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'error-fixed': '#ba1a1a',
        'on-error-fixed': '#ffffff',
        'on-error-fixed-variant': '#7a0908',
        emerald: {
          50: '#f0fdf4',
          700: '#15803d',
        },
        slate: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          600: '#475569',
          700: '#334155',
        },
        indigo: {
          50: '#eef2ff',
          700: '#3730a3',
        },
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      boxShadow: {
        'soft': '0px 1px 3px rgba(0,0,0,0.05), 0px 10px 15px -3px rgba(0,0,0,0.03)',
        'elevated': '0px 4px 6px rgba(0,0,0,0.07)',
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
};
